pool: eran-mbpr

stages:
  - stage: build
    jobs:
      - job : build
        steps:
        # - task: Bash@3
        #   inputs:
        #     targetType: 'inline'
        #     script: |
        #       # Write your commands here
        #       docker build -t backend:latest backend -f ./backend/Dockerfile
        - task: Docker@2
          inputs:
            containerRegistry: 'dh-erhansiraci'
            repository: 'backend'
            command: 'build'
            Dockerfile: './backend/Dockerfile'
            tags: $(Build.SourceVersion)
            buildContext: './backend'
  - stage: test
    jobs:
      - job : unitTest
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              echo RUN UNIT TEST
      - job : staticCodeAnalysis
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              echo RUN STATIC CODE ANALYSIS              
  - stage: securityCheck
    jobs:
      - job : scanImage
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              docker scout quickview backend:$(Build.SourceVersion)
              docker scout cves backend:$(Build.SourceVersion)
  - stage: publish
    jobs:
      - job : pushImage
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              echo RUN IMAGE PUSH              
  - stage: deploy
    jobs:
      - job : deployInt
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              echo RUN DEPLOY to INT
              # ll
              # docker compose up -d --build
