pool: eran-mbpr

stages:
  - stage: build
    jobs:
      - job : build
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'dh-erhansiraci'
            repository: 'erhansiraci/backend'
            command: 'build'
            Dockerfile: './backend/Dockerfile'
            tags: $(Build.SourceVersion)
            buildContext: './backend'
  - stage: test
    jobs:
      - job : unitTest
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              echo RUN UNIT TEST
      - job : staticCodeAnalysis
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              echo RUN STATIC CODE ANALYSIS              
  - stage: securityCheck
    jobs:
      - job : scanImage
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              docker scout quickview erhansiraci/backend:$(Build.SourceVersion)
              docker scout cves erhansiraci/backend:$(Build.SourceVersion)

  - stage: publish
    jobs:
      - job : pushImage
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              docker push erhansiraci/backend:$(Build.SourceVersion)
  - stage: deploy
    jobs:
      - job : deployInt
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              echo RUN DEPLOY to INT
              docker run -d -p80:80 erhansiraci/backend:$(Build.SourceVersion)
