pool: eran-mbpr

stages:
  - stage: build
    jobs:
      - job : build
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'dh-erhansiraci'
            repository: 'erhansiraci/backend'
            command: 'build'
            Dockerfile: './backend/Dockerfile'
            buildContext: './backend'
            tags: '$(Build.SourceVersion)'
        - task: Docker@2
          inputs:
            containerRegistry: 'dh-erhansiraci'
            repository: 'erhansiraci/frontend'
            command: 'build'
            Dockerfile: './frontend/Dockerfile'
            buildContext: './frontend'
            tags: '$(Build.SourceVersion)'

  - stage: test
    jobs:
      - job : unitTest
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              echo RUN UNIT TEST
      - job : staticCodeAnalysis
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              echo RUN STATIC CODE ANALYSIS              
  - stage: securityCheck
    jobs:
      - job : scanImage
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              docker scout quickview erhansiraci/backend:$(Build.SourceVersion)
              docker scout cves erhansiraci/backend:$(Build.SourceVersion)
              docker scout quickview erhansiraci/frontend:$(Build.SourceVersion)
              docker scout cves erhansiraci/frontend:$(Build.SourceVersion)
  - stage: publish
    jobs:
      - job : pushImage
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              docker push erhansiraci/backend:$(Build.SourceVersion)
              docker push erhansiraci/frontend:$(Build.SourceVersion)
  - stage: deploy
    jobs:
      - job : deployInt
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              echo RUN DEPLOY to INT
              export BACKEND=$(Build.SourceVersion)
              export FRONTEND=$(Build.SourceVersion)
              export REDIS_PASSWORD=123456ex
              export REDIS_CONNECTION_STRING=cloud-week12-lab-1-redis-1:6379,password=123456ex
              docker compose --project-name cloud-week12-lab-1 up -d
