version: "3"

services:
  backend:
    # build: ./backend
    image: "erhansiraci/backend:${BACKEND}"
    ports:
      - 80:80
    networks:
      - vNet
  frontend:
    # build: ./frontend
    image: "erhansiraci/frontend:${FRONTEND}"
    ports:
      - 8080:80
    networks:
      - vNet
  redis:
    image: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass 123456ex
    networks:
      - vNet
networks:
  vNet:
    driver: bridge
